import type { AssignedMenuProduct } from './types';

const assignedMenuProductsBase: Omit<AssignedMenuProduct, 'menuId'>[] = [
  {
    id: 'amp-1',
    menuName: 'Fast Food',
    name: 'Chicken Burger',
    category: 'Fast Food',
    price: 550,
    addon: 'Extra Toppings',
    unitOfMeasure: 'Per KG',
    stockQuantity: 120,
    inStock: true,
    isActive: true,
  },
  {
    id: 'amp-2',
    menuName: 'Fast Food',
    name: 'Zinger Burger',
    category: 'Fast Food',
    price: 650,
    addon: 'Cheese Slice',
    unitOfMeasure: 'Per KG',
    stockQuantity: 80,
    inStock: true,
    isActive: true,
  },
  {
    id: 'amp-3',
    menuName: 'Fast Food',
    name: 'Crispy Wrap',
    category: 'Fast Food',
    price: 500,
    addon: 'Garlic Mayo',
    unitOfMeasure: 'Per KG',
    stockQuantity: 25,
    inStock: false,
    isActive: false,
  },
  {
    id: 'amp-4',
    menuName: 'BBQ Specials',
    name: 'Chicken Tikka',
    category: 'BBQ',
    price: 850,
    addon: 'Mint Sauce',
    unitOfMeasure: 'Per KG',
    stockQuantity: 200,
    inStock: true,
    isActive: true,
  },
  {
    id: 'amp-5',
    menuName: 'BBQ Specials',
    name: 'Beef Seekh Kebab',
    category: 'BBQ',
    price: 750,
    addon: 'Onion Salad',
    unitOfMeasure: 'Per KG',
    stockQuantity: 120,
    inStock: true,
    isActive: true,
  },
  {
    id: 'amp-6',
    menuName: 'BBQ Specials',
    name: 'Mutton Boti',
    category: 'BBQ',
    price: 990,
    addon: 'Special Chutney',
    unitOfMeasure: 'Per KG',
    stockQuantity: 10,
    inStock: false,
    isActive: false,
  },
  {
    id: 'amp-7',
    menuName: 'Healthy Bites',
    name: 'Grilled Chicken Salad',
    category: 'Healthy',
    price: 620,
    addon: 'Olive Mix',
    unitOfMeasure: 'Per KG',
    stockQuantity: 25,
    inStock: true,
    isActive: true,
  },
  {
    id: 'amp-8',
    menuName: 'Healthy Bites',
    name: 'Quinoa Bowl',
    category: 'Healthy',
    price: 700,
    addon: 'Avocado',
    unitOfMeasure: 'Per KG',
    stockQuantity: 0,
    inStock: false,
    isActive: false,
  },
  {
    id: 'amp-9',
    menuName: 'Healthy Bites',
    name: 'Protein Wrap',
    category: 'Healthy',
    price: 580,
    addon: 'Greek Yogurt Dip',
    unitOfMeasure: 'Per KG',
    stockQuantity: 127,
    inStock: true,
    isActive: true,
  },
  {
    id: 'amp-10',
    menuName: 'Street Snacks',
    name: 'Loaded Fries',
    category: 'Snacks',
    price: 420,
    addon: 'Jalapeno Mayo',
    unitOfMeasure: 'Per KG',
    stockQuantity: 92,
    inStock: true,
    isActive: true,
  },
  {
    id: 'amp-11',
    menuName: 'Street Snacks',
    name: 'Chicken Shawarma',
    category: 'Snacks',
    price: 480,
    addon: 'Garlic Sauce',
    unitOfMeasure: 'Per KG',
    stockQuantity: 0,
    inStock: false,
    isActive: false,
  },
  {
    id: 'amp-12',
    menuName: 'Seafood Feast',
    name: 'Grilled Fish',
    category: 'Seafood',
    price: 1200,
    addon: 'Herb Butter',
    unitOfMeasure: 'Per KG',
    stockQuantity: 34,
    inStock: true,
    isActive: true,
  },
  {
    id: 'amp-13',
    menuName: 'Seafood Feast',
    name: 'Crispy Prawns',
    category: 'Seafood',
    price: 1380,
    addon: 'Tartar Dip',
    unitOfMeasure: 'Per KG',
    stockQuantity: 9,
    inStock: false,
    isActive: false,
  },
  {
    id: 'amp-14',
    menuName: 'Pizza Corner',
    name: 'Pepperoni Pizza',
    category: 'Pizza',
    price: 1450,
    addon: 'Cheese Burst',
    unitOfMeasure: 'Per KG',
    stockQuantity: 47,
    inStock: true,
    isActive: true,
  },
  {
    id: 'amp-15',
    menuName: 'Pizza Corner',
    name: 'Veggie Pizza',
    category: 'Pizza',
    price: 1150,
    addon: 'Black Olives',
    unitOfMeasure: 'Per KG',
    stockQuantity: 23,
    inStock: true,
    isActive: true,
  },
  {
    id: 'amp-16',
    menuName: 'Dessert Bar',
    name: 'Chocolate Lava Cake',
    category: 'Dessert',
    price: 390,
    addon: 'Vanilla Scoop',
    unitOfMeasure: 'Per KG',
    stockQuantity: 18,
    inStock: true,
    isActive: true,
  },
  {
    id: 'amp-17',
    menuName: 'Dessert Bar',
    name: 'Blueberry Cheesecake',
    category: 'Dessert',
    price: 510,
    addon: 'Berry Compote',
    unitOfMeasure: 'Per KG',
    stockQuantity: 0,
    inStock: false,
    isActive: false,
  },
  {
    id: 'amp-18',
    menuName: 'Breakfast Club',
    name: 'Pancake Stack',
    category: 'Breakfast',
    price: 460,
    addon: 'Maple Syrup',
    unitOfMeasure: 'Per KG',
    stockQuantity: 65,
    inStock: true,
    isActive: true,
  },
  {
    id: 'amp-19',
    menuName: 'Breakfast Club',
    name: 'Omelette Platter',
    category: 'Breakfast',
    price: 530,
    addon: 'Cheddar',
    unitOfMeasure: 'Per KG',
    stockQuantity: 42,
    inStock: true,
    isActive: true,
  },
  {
    id: 'amp-20',
    menuName: 'Pasta House',
    name: 'Alfredo Pasta',
    category: 'Pasta',
    price: 860,
    addon: 'Grilled Chicken',
    unitOfMeasure: 'Per KG',
    stockQuantity: 31,
    inStock: true,
    isActive: true,
  },
  {
    id: 'amp-21',
    menuName: 'Pasta House',
    name: 'Arrabbiata Pasta',
    category: 'Pasta',
    price: 780,
    addon: 'Parmesan',
    unitOfMeasure: 'Per KG',
    stockQuantity: 6,
    inStock: false,
    isActive: false,
  },
  {
    id: 'amp-22',
    menuName: 'Rice & Curry',
    name: 'Chicken Biryani',
    category: 'Rice',
    price: 690,
    addon: 'Raita',
    unitOfMeasure: 'Per KG',
    stockQuantity: 110,
    inStock: true,
    isActive: true,
  },
  {
    id: 'amp-23',
    menuName: 'Rice & Curry',
    name: 'Beef Pulao',
    category: 'Rice',
    price: 740,
    addon: 'Salad',
    unitOfMeasure: 'Per KG',
    stockQuantity: 22,
    inStock: true,
    isActive: true,
  },
];

export const assignedMenuProductsMock: AssignedMenuProduct[] =
  assignedMenuProductsBase.map((item) => ({
    ...item,
    menuId: item.menuName
      .toLowerCase()
      .replace(/\s+/g, '-')
      .replace(/[^a-z0-9-]/g, ''),
  }));
