import { ZoneCommissionData } from '../../types';

// Mock data for Zone Based Commission Table
export const zoneCommissionData: ZoneCommissionData[] = [
  {
    id: '1',
    zone: 'Islamabad',
    defaultCommission: '12%',
    shopTypeCommission: '10%',
    minimumPayout: 'PKR 500',
    status: 'Active',
  },
  {
    id: '2',
    zone: 'Lahore',
    defaultCommission: '15%',
    shopTypeCommission: '10%',
    minimumPayout: 'PKR 500',
    status: 'Active',
  },
  {
    id: '3',
    zone: 'Karachi',
    defaultCommission: '15%',
    shopTypeCommission: '10%',
    minimumPayout: 'PKR 500',
    status: 'Active',
  },
  {
    id: '4',
    zone: 'Karachi',
    defaultCommission: '15%',
    shopTypeCommission: '10%',
    minimumPayout: 'PKR 500',
    status: 'Active',
  },
  {
    id: '5',
    zone: 'Karachi',
    defaultCommission: '15%',
    shopTypeCommission: '10%',
    minimumPayout: 'PKR 500',
    status: 'Active',
  },
  {
    id: '6',
    zone: 'Karachi',
    defaultCommission: '15%',
    shopTypeCommission: '10%',
    minimumPayout: 'PKR 500',
    status: 'Active',
  },
  {
    id: '7',
    zone: 'Islamabad',
    defaultCommission: '20%',
    shopTypeCommission: '10%',
    minimumPayout: 'PKR 500',
    status: 'Inactive',
  },
  {
    id: '8',
    zone: 'Lahore',
    defaultCommission: '20%',
    shopTypeCommission: '10%',
    minimumPayout: 'PKR 500',
    status: 'Active',
  },
  {
    id: '9',
    zone: 'Peshawar',
    defaultCommission: '20%',
    shopTypeCommission: '10%',
    minimumPayout: 'PKR 700',
    status: 'Inactive',
  },
  {
    id: '10',
    zone: 'Faisalabad',
    defaultCommission: '20%',
    shopTypeCommission: '10%',
    minimumPayout: 'PKR 800',
    status: 'Active',
  },
  {
    id: '11',
    zone: 'Karachi',
    defaultCommission: '20%',
    shopTypeCommission: '10%',
    minimumPayout: 'PKR 900',
    status: 'Active',
  },
  {
    id: '12',
    zone: 'Multan',
    defaultCommission: '20%',
    shopTypeCommission: '10%',
    minimumPayout: 'PKR 1000',
    status: 'Active',
  },
];
