
export const riderTable = [
    {
        "id": "RID-001",
        "name": "Alex Rivera",
        "phone": "+1-555-0101",
        "email": "alex.r@fleet.com",
        "zone": "Downtown",
        "vehicle_type": "Bicycle",
        "total_deliveries": 1240,
        "total_earnings": 8450.00,
        "registration_date": "2023-05-12",
        "ratings": 4.8,
        "status": "Active",
        "rejectionReason": null,
        "VehicleBrand": "Trek",
        "modelYear": 2022,
        "vehicleColor": "Blue",
        "VehicleNumber": "BIC-001",
        "createdAt": "2023-05-12T00:00:00Z"
    },
    {
        "id": "RID-002",
        "name": "Sarah Chen",
        "phone": "+1-555-0102",
        "email": "schen.delivery@mail.com",
        "zone": "North Heights",
        "vehicle_type": "E-Bike",
        "total_deliveries": 850,
        "total_earnings": 5120.50,
        "registration_date": "2023-08-20",
        "ratings": 4.9,
        "status": "Blocked",
        "rejectionReason": null,
        "VehicleBrand": "Rad Power Bikes",
        "modelYear": 2023,
        "vehicleColor": "Black",
        "VehicleNumber": "EBK-002",
        "createdAt": "2023-08-20T00:00:00Z"
    },
    {
        "id": "RID-003",
        "name": "Marcus Jordan",
        "phone": "+1-555-0103",
        "email": "m.jordan92@web.com",
        "zone": "West End",
        "vehicle_type": "Motorcycle",
        "total_deliveries": 2100,
        "total_earnings": 14200.00,
        "registration_date": "2022-11-05",
        "ratings": 4.5,
        "status": "Rejected",
        "rejectionReason": "Failed background check",
        "VehicleBrand": "Honda",
        "modelYear": 2021,
        "vehicleColor": "Red",
        "VehicleNumber": "MOT-003",
        "createdAt": "2022-11-05T00:00:00Z"
    },
    {
        "id": "RID-004",
        "name": "Elena Rodriguez",
        "phone": "+1-555-0104",
        "email": "elena.rod@provider.com",
        "zone": "Southside",
        "vehicle_type": "Car",
        "total_deliveries": 430,
        "total_earnings": 3800.75,
        "registration_date": "2024-01-15",
        "ratings": 4.7,
        "status": "Active",
        "rejectionReason": null,
        "VehicleBrand": "Toyota",
        "modelYear": 2020,
        "vehicleColor": "White",
        "VehicleNumber": "CAR-004",
        "createdAt": "2024-01-15T00:00:00Z"
    },
    {
        "id": "RID-005",
        "name": "Jamie Smith",
        "phone": "+1-555-0105",
        "email": "jsmith.logistics@mail.com",
        "zone": "Downtown",
        "vehicle_type": "Scooter",
        "total_deliveries": 15,
        "total_earnings": 120.00,
        "registration_date": "2024-03-01",
        "ratings": 0.0,
        "status": "Pending",
        "rejectionReason": null,
        "VehicleBrand": "Vespa",
        "modelYear": 2023,
        "vehicleColor": "Green",
        "VehicleNumber": "SCT-005",
        "createdAt": "2024-03-01T00:00:00Z"
    },
    {
        "id": "RID-006",
        "name": "Taylor Wong",
        "phone": "+1-555-0106",
        "email": "t.wong@fastmail.com",
        "zone": "East Bay",
        "vehicle_type": "E-Bike",
        "total_deliveries": 960,
        "total_earnings": 6340.25,
        "registration_date": "2023-06-10",
        "ratings": 4.6,
        "status": "Blocked",
        "rejectionReason": null,
        "VehicleBrand": "Specialized",
        "modelYear": 2022,
        "vehicleColor": "Silver",
        "VehicleNumber": "EBK-006",
        "createdAt": "2023-06-10T00:00:00Z"
    },
    {
        "id": "RID-007",
        "name": "Priya Kapoor",
        "phone": "+1-555-0107",
        "email": "p.kapoor@service.org",
        "zone": "Central Park",
        "vehicle_type": "Bicycle",
        "total_deliveries": 612,
        "total_earnings": 4100.00,
        "registration_date": "2023-09-18",
        "ratings": 4.8,
        "status": "pending",
        "rejectionReason": null,
        "VehicleBrand": "Giant",
        "modelYear": 2023,
        "vehicleColor": "Yellow",
        "vehicleNumber": "BIC-007",
        "createdAt": "2023-09-18T00:00:00Z"
    },
    {
        "id": "RID-008",
        "name": "David Miller",
        "phone": "+1-555-0108",
        "email": "dmiller.deliver@webmail.com",
        "zone": "West End",
        "vehicle_type": "Motorcycle",
        "total_deliveries": 1540,
        "total_earnings": 9850.50,
        "registration_date": "2023-02-22",
        "ratings": 4.4,
        "status": "Rejected",
        "rejectionReason": "Invalid license",
        "VehicleBrand": "Yamaha",
        "modelYear": 2022,
        "vehicleColor": "Black",
        "VehicleNumber": "MOT-008",
        "createdAt": "2023-02-22T00:00:00Z"
    }
]
