import { StoreCommissionData } from '../../types';

export const storeCommissionData: StoreCommissionData[] = [
  {
    id: '1',
    storeName: 'KFC F-7',
    vendor: 'KFC',
    zone: 'Islamabad',
    defaultCommission: '15%',
    status: 'Active',
  },
  {
    id: '2',
    storeName: 'KFC F-10',
    vendor: 'KFC',
    zone: 'Islamabad',
    defaultCommission: '13%',
    status: 'Active',
  },
  {
    id: '3',
    storeName: 'KFC DHA',
    vendor: 'KFC',
    zone: 'Lahore',
    defaultCommission: '15%',
    status: 'Active',
  },
  {
    id: '4',
    storeName: 'Grocery',
    vendor: 'Grocery',
    zone: 'Karachi',
    defaultCommission: '12%',
    status: 'Inactive',
  },
  {
    id: '5',
    storeName: 'Pizza Max Golra',
    vendor: 'Pizza Max',
    zone: 'Islamabad',
    defaultCommission: '15%',
    status: 'Active',
  },
  {
    id: '6',
    storeName: 'Pizza Max DHA',
    vendor: 'Pizza Max',
    zone: 'Lahore',
    defaultCommission: '15%',
    status: 'Active',
  },
  {
    id: '7',
    storeName: 'Burger King Centaurus',
    vendor: 'Burger King',
    zone: 'Islamabad',
    defaultCommission: '15%',
    status: 'Active',
  },
  {
    id: '8',
    storeName: 'Subway Blue Area',
    vendor: 'Subway',
    zone: 'Islamabad',
    defaultCommission: '10%',
    status: 'Active',
  },
  {
    id: '9',
    storeName: 'Subway DHA',
    vendor: 'Subway',
    zone: 'Karachi',
    defaultCommission: '10%',
    status: 'Inactive',
  },
  {
    id: '10',
    storeName: 'Cheezious F-11',
    vendor: 'Cheezious',
    zone: 'Islamabad',
    defaultCommission: '20%',
    status: 'Active',
  },
  {
    id: '11',
    storeName: 'Cheezious I-8',
    vendor: 'Cheezious',
    zone: 'Islamabad',
    defaultCommission: '20%',
    status: 'Active',
  },
  {
    id: '12',
    storeName: "Gloria Jean's F-6",
    vendor: "Gloria Jean's",
    zone: 'Islamabad',
    defaultCommission: '15%',
    status: 'Inactive',
  },
];
