import type { RefundRequestRecord } from './types';

export const refundRequestsMockData: RefundRequestRecord[] = [
  {
    id: 'rf-0020',
    requestId: 'WR-00124',
    orderId: 'OR-00124',
    customerName: 'Maria Khalid',
    customerAvatar: 'https://i.pravatar.cc/100?img=43',
    customerEmail: 'maria.khalid@example.com',
    customerPhone: '+92 300 1234567',
    storeName: 'FlavorWorks',
    storeAvatar: 'https://i.pravatar.cc/100?img=14',
    riderName: 'Kamran Ali',
    riderAvatar: 'https://i.pravatar.cc/100?img=12',
    refundType: 'full',
    amountUsd: 56,
    requestDate: '2025-11-12',
    status: 'approved',
    paymentType: 'Online',
    reason: 'Order was delivered late and food was cold. Missing items in the order.',
    items: [
      { id: '1', name: 'Chicken Wrap', quantity: 2, unitPriceUsd: 28 },
      { id: '2', name: 'Garlic Bread', quantity: 2, unitPriceUsd: 14 },
    ],
    activityLogs: [
      {
        id: 'log-1',
        action: 'Request approved with loyalty points adjustment.',
        actor: 'Admin',
        createdAt: '2025-11-12T11:20:00Z',
      },
    ],
  },
  {
    id: 'rf-0021',
    requestId: 'WR-00125',
    orderId: 'OR-00125',
    customerName: 'Ahmed Raza',
    customerAvatar: 'https://i.pravatar.cc/100?img=58',
    customerEmail: 'ahmed.raza@example.com',
    customerPhone: '+92 311 7889921',
    storeName: 'Golden Spoon Foods',
    storeAvatar: 'https://i.pravatar.cc/100?img=20',
    riderName: 'Ahmed Raza',
    riderAvatar: 'https://i.pravatar.cc/100?img=58',
    refundType: 'partial',
    amountUsd: 78,
    requestDate: '2025-11-12',
    status: 'rejected',
    paymentType: 'Cash',
    reason: 'Customer requested a partial refund due to missing side item.',
    items: [{ id: '1', name: 'Family Deal', quantity: 1, unitPriceUsd: 78 }],
    activityLogs: [],
  },
  {
    id: 'rf-0022',
    requestId: 'WR-00126',
    orderId: 'OR-00126',
    customerName: 'Saira Mehmood',
    customerAvatar: 'https://i.pravatar.cc/100?img=47',
    customerEmail: 'saira.mehmood@example.com',
    customerPhone: '+92 333 2299881',
    storeName: 'FreshBite Co.',
    storeAvatar: 'https://i.pravatar.cc/100?img=33',
    riderName: 'Saira Mehmood',
    riderAvatar: 'https://i.pravatar.cc/100?img=47',
    refundType: 'full',
    amountUsd: 67,
    requestDate: '2025-11-12',
    status: 'pending',
    paymentType: 'Online',
    reason: 'Food quality issue reported by customer.',
    items: [{ id: '1', name: 'Crispy Chicken Meal', quantity: 1, unitPriceUsd: 67 }],
    activityLogs: [],
  },
  {
    id: 'rf-0023',
    requestId: 'WR-00127',
    orderId: 'OR-00127',
    customerName: 'Bilal Ahmed',
    customerAvatar: 'https://i.pravatar.cc/100?img=54',
    customerEmail: 'bilal.ahmed@example.com',
    customerPhone: '+92 322 4172812',
    storeName: 'Tasty Trails',
    storeAvatar: 'https://i.pravatar.cc/100?img=41',
    riderName: 'Bilal Ahmed',
    riderAvatar: 'https://i.pravatar.cc/100?img=54',
    refundType: 'full',
    amountUsd: 89,
    requestDate: '2025-11-12',
    status: 'pending',
    paymentType: 'Online',
    reason: 'Duplicate order charged to customer account.',
    items: [{ id: '1', name: 'Family Platter', quantity: 1, unitPriceUsd: 89 }],
    activityLogs: [],
  },
  {
    id: 'rf-0024',
    requestId: 'WR-00128',
    orderId: 'OR-00128',
    customerName: 'Fatima Khan',
    customerAvatar: 'https://i.pravatar.cc/100?img=24',
    customerEmail: 'fatima.khan@example.com',
    customerPhone: '+92 344 8799012',
    storeName: 'Urban Harvest Catering',
    storeAvatar: 'https://i.pravatar.cc/100?img=22',
    riderName: 'Fatima Khan',
    riderAvatar: 'https://i.pravatar.cc/100?img=24',
    refundType: 'partial',
    amountUsd: 98,
    requestDate: '2025-11-12',
    status: 'approved',
    paymentType: 'Online',
    reason: 'One item was not delivered.',
    items: [{ id: '1', name: 'Lunch Box', quantity: 4, unitPriceUsd: 24.5 }],
    activityLogs: [],
  },
  {
    id: 'rf-0025',
    requestId: 'WR-00129',
    orderId: 'OR-00129',
    customerName: 'Maria Khalid',
    customerAvatar: 'https://i.pravatar.cc/100?img=43',
    customerEmail: 'maria.khalid@example.com',
    customerPhone: '+92 300 1234567',
    storeName: 'FlavorWorks',
    storeAvatar: 'https://i.pravatar.cc/100?img=14',
    riderName: 'Maria Khalid',
    riderAvatar: 'https://i.pravatar.cc/100?img=43',
    refundType: 'full',
    amountUsd: 79,
    requestDate: '2025-11-12',
    status: 'approved',
    paymentType: 'Cash',
    reason: 'Wrong order delivered.',
    items: [{ id: '1', name: 'Combo Pack', quantity: 1, unitPriceUsd: 79 }],
    activityLogs: [],
  },
  {
    id: 'rf-0026',
    requestId: 'WR-00123',
    orderId: 'OR-00123',
    customerName: 'Ahmed Raza',
    customerAvatar: 'https://i.pravatar.cc/100?img=58',
    customerEmail: 'ahmed.raza@example.com',
    customerPhone: '+92 311 7889921',
    storeName: 'Golden Spoon Foods',
    storeAvatar: 'https://i.pravatar.cc/100?img=20',
    riderName: 'Ahmed Raza',
    riderAvatar: 'https://i.pravatar.cc/100?img=58',
    refundType: 'partial',
    amountUsd: 74,
    requestDate: '2025-11-12',
    status: 'pending',
    paymentType: 'Online',
    reason: 'Packaging was damaged upon arrival.',
    items: [{ id: '1', name: 'Premium Combo', quantity: 1, unitPriceUsd: 74 }],
    activityLogs: [],
  },
  {
    id: 'rf-0027',
    requestId: 'WR-00122',
    orderId: 'OR-00122',
    customerName: 'Saira Mehmood',
    customerAvatar: 'https://i.pravatar.cc/100?img=47',
    customerEmail: 'saira.mehmood@example.com',
    customerPhone: '+92 333 2299881',
    storeName: 'FreshBite Co.',
    storeAvatar: 'https://i.pravatar.cc/100?img=33',
    riderName: 'Saira Mehmood',
    riderAvatar: 'https://i.pravatar.cc/100?img=47',
    refundType: 'full',
    amountUsd: 64,
    requestDate: '2025-11-12',
    status: 'rejected',
    paymentType: 'Cash',
    reason: 'Request outside policy window.',
    items: [{ id: '1', name: 'Chicken Meal', quantity: 1, unitPriceUsd: 64 }],
    activityLogs: [],
  },
  {
    id: 'rf-0028',
    requestId: 'WR-00121',
    orderId: 'OR-00121',
    customerName: 'Bilal Ahmed',
    customerAvatar: 'https://i.pravatar.cc/100?img=54',
    customerEmail: 'bilal.ahmed@example.com',
    customerPhone: '+92 322 4172812',
    storeName: 'Tasty Trails',
    storeAvatar: 'https://i.pravatar.cc/100?img=41',
    riderName: 'Bilal Ahmed',
    riderAvatar: 'https://i.pravatar.cc/100?img=54',
    refundType: 'full',
    amountUsd: 62,
    requestDate: '2025-11-12',
    status: 'rejected',
    paymentType: 'Online',
    reason: 'Customer confirmed issue resolved directly with store.',
    items: [{ id: '1', name: 'Special Combo', quantity: 1, unitPriceUsd: 62 }],
    activityLogs: [],
  },
];

export const getRefundRequestById = (requestId: string) =>
  refundRequestsMockData.find(
    (request) =>
      request.id.toLowerCase() === requestId.toLowerCase() ||
      request.requestId.toLowerCase() === requestId.toLowerCase(),
  );
