
export const earningViewTableData = [
    {
        // Type definition for earnings data


        orderId: "ORD-001",
        customerName: "John Smith",
        customerImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
        zoneType: "Urban",
        vendorName: "Pizza Palace",
        orderAmount: 25.99,
        branchName: "Downtown Branch",
        commissionValue: 3.90,
        deliveryFee: 2.50,
        paymentMethod: "Credit Card",
        date: "2024-01-15",
        status: "Completed"
    },
    {
        orderId: "ORD-002",
        customerName: "Sarah Johnson",
        customerImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop",
        zoneType: "Suburban",
        vendorName: "Burger King",
        orderAmount: 18.75,
        branchName: "Mall Location",
        commissionValue: 2.81,
        deliveryFee: 3.00,
        paymentMethod: "PayPal",
        date: "2024-01-16",
        status: "Completed"
    },
    {
        orderId: "ORD-003",
        customerName: "Mike Davis",
        customerImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
        zoneType: "Rural",
        vendorName: "Taco Bell",
        orderAmount: 32.50,
        branchName: "Highway Store",
        commissionValue: 4.88,
        deliveryFee: 4.50,
        paymentMethod: "Cash",
        date: "2024-01-17",
        status: "Completed"
    },
    {
        orderId: "ORD-004",
        customerName: "Emily Wilson",
        customerImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop",
        zoneType: "Urban",
        vendorName: "Subway",
        orderAmount: 12.99,
        branchName: "City Center",
        commissionValue: 1.95,
        deliveryFee: 2.00,
        paymentMethod: "Debit Card",
        date: "2024-01-18",
        status: "Completed"
    },
    {
        orderId: "ORD-005",
        customerName: "David Brown",
        customerImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
        zoneType: "Suburban",
        vendorName: "KFC",
        orderAmount: 28.45,
        branchName: "Westside Branch",
        commissionValue: 4.27,
        deliveryFee: 3.50,
        paymentMethod: "Credit Card",
        date: "2024-01-19",
        status: "Completed"
    },
    {
        orderId: "ORD-006",
        customerName: "Lisa Anderson",
        customerImage: "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=200&h=200&fit=crop",
        zoneType: "Urban",
        vendorName: "McDonald's",
        orderAmount: 15.80,
        branchName: "Main Street",
        commissionValue: 2.37,
        deliveryFee: 2.25,
        paymentMethod: "Mobile Pay",
        date: "2024-01-20",
        status: "Completed"
    },
    {
        orderId: "ORD-007",
        customerName: "Robert Taylor",
        customerImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
        zoneType: "Rural",
        vendorName: "Domino's Pizza",
        orderAmount: 41.20,
        branchName: "North Branch",
        commissionValue: 6.18,
        deliveryFee: 5.00,
        paymentMethod: "Credit Card",
        date: "2024-01-21",
        status: "Completed"
    },
    {
        orderId: "ORD-008",
        customerName: "Jennifer Martinez",
        customerImage: "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=200&h=200&fit=crop",
        zoneType: "Suburban",
        vendorName: "Chipotle",
        orderAmount: 22.35,
        branchName: "Shopping Plaza",
        commissionValue: 3.35,
        deliveryFee: 2.75,
        paymentMethod: "PayPal",
        date: "2024-01-22",
        status: "Completed"
    },
    {
        orderId: "ORD-009",
        customerName: "Christopher Lee",
        customerImage: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop",
        zoneType: "Urban",
        vendorName: "Starbucks",
        orderAmount: 8.95,
        branchName: "Business District",
        commissionValue: 1.34,
        deliveryFee: 1.50,
        paymentMethod: "Mobile Pay",
        date: "2024-01-23",
        status: "Completed"
    },
    {
        orderId: "ORD-010",
        customerName: "Amanda White",
        customerImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
        zoneType: "Rural",
        vendorName: "Papa John's",
        orderAmount: 35.60,
        branchName: "County Road",
        commissionValue: 5.34,
        deliveryFee: 4.25,
        paymentMethod: "Cash",
        date: "2024-01-24",
        status: "Completed"
    }
];
